### ISSUE TITLE
Claim 3.3.11.

### ISSUE THREAD

**Issue by timotejsujan** [clambiehanson/teaching#1]
The subclaim in Claim 3.3.11. stating that  $Z' \cap Y \supseteq W'$ is not that immediate, since there is no proof that $Y \supseteq W'$.

**Comment by clambiehanson** [comment]
Thanks! There was a bug in the definition of H; it needed to be upward closed. It's been fixed now.

**Comment by timotejsujan** [comment]
Perfect, much appreciated!
